services:
  api:
    image: starwars-data-proxy:api-dev
    command: ./api server
    network_mode: "host"
    volumes:
    - ./:/app
    working_dir: "/app"
    env_file:
      - .env
    ports:
      - "8080:8080"
